### ISSUE TITLE
Como mostrar os gráficos ao público

### ISSUE THREAD

**Issue by fvall** [brasil-em-numeros/brasil-em-numeros#14]
@juliano 

Estive pensando nessa sexta-feira qual seria melhor forma de mostrar a informação ao usuário. Vendo os dados reais de maio, cheguei a conclusão que fazer um gráfico com muita interatividade, onde o usuário é capaz de filter/procurar pelos dados que ele quer é relativamente difícil, pois os dados não são tão uniformizados como eu gostaria.

Há uma grande variabilidade nos valores dos gastos (por exemplo, ministério da economia vs ministério da agricultura), o que faz os gráficos ficaram facilmente desproporcionais. Usuários com maior facilidade em manejar gráficos poderiam fazer uso dessa ferramenta, mas creio que a grande maioria teria dificuldade de ver os dados de uma forma concisa e clara.

Pensando nisso, eu criei duas branches (modo1 e modo2) com duas abordagens.

## Modo 1 : Poucos gráficos com muita informação e alta interatividade

Nessa branch eu coloquei um treemap, onde você pode ver em detalhe cada "quadrado" com um double-click. Você também pode filtrar com os dropdown ao lado, que limita os dados para melhorar o foco da análise.

### Pros

- O usuário pode ver "o que quiser"
- "Wow factor"
- Conseguiríamos resumir muitos dados em uma forma concisa
- Não há muito processamento de dados para ser feito _**antes**_ dos dados chegarem no Python

### Cons

- Para quem não entende, fica difícil de usar a ferramenta
- Muitos dados teriam que ser guardados em memória durante o runtime para podermos executar todos os filtros e interatividade.

## Modo 2 : Maior quantidade de gráficos, porém mais específicos e com menos interatividade

 Nessa branch eu coloquei dois gráficos mais específicos e tirei o JS que executava os filtros. Os gráficos tem alguma interatividade (pode selecionar cada item da legenda, por exemplo) porém bem menor que na outra branch.

Se os gráficos forem feitos dessa forma, nós poderíamos facilitar a vida do usuário e já mostrar os dados que realmente interessam e/ou que fazem sentido para alguma análise.

### Pros

- Usuários não habituados em mexer com gráficos podem simplesmente ver os resultados
- Mais específico geralmente significa códigos mais simples
- Menos JavaScript e comunicação Python <==> JS
- Mais fácil de usar no telefone

### Cons

- Mais processamento fora de Python (mini-csvs)
- Mais trabalho no back-end
  - Temos que pensar o que é interessante em cada dataset
  - Temos que "adivinhar" o que cada usuário quer ver

---

Eu quando imaginei o projeto eu estava inclinado em prosseguir o modo 1, mas depois de sexta-feira eu comecei a tender na direção do modo 2. Acho que para a maioria das pessoas, elas só querem saber de como o governo está atuando, e não está necessariamente interessada em descobrir a informação por si mesma.

@juliano  - qual a sua opinião?

**Comment by fvall** [comment]
Outra coisa que deixa isso mais difícil é entender o que são essas despesas negativas. Por exemplo: o que são esses -325K do ministério da economia relacionado a COVID-19??

**Comment by juliano** [comment]
Eu acho que devemos começar pelo modo 2 por uma variedade de razões:

- Ao contrário de você, eu pensei em começar pelo modo 2 desde o inicio (essas soa como se estivéssemos pra sair no braço né? :P)
- Depois da nossa conversa sobre a landing page, comecei a pensar em como disponibilizar os dados de forma educativa: o primeiro gráfico pra chamar a atenção seria extremamente simples (digamos ministérios, algo que todo mundo já ouviu falar), dae direcionamos o usuário pro próximo nível, e por aí vai. Isso leva ao próximo ponto.
- Saber manipular o gráfico não pode ser um requerimento: mesmo que seja possível fazê-lo, alguém muito leigo vai pensar que é uma imagem e mesmo assim tirar algum conhecimento dali.
- Mesmo que tenhamos que adivinhar, não vejo como um problema se tomarmos a abordagem educativa, pois vamos guiar o usuário.

Na parte técnica, só vejo vantagens. O código será mais simples, os mini-csvs já se faziam necessários devido a quantidade de dados que temos: eu já estava planejando ir nessa direção após implementar #15 

Isso dito, creio que vamos implementar o modo 1 no futuro, onde usuários mais experientes possam explorar os dados em detalhes.

Por fim, os problemas com os dados. Não sei se é apenas preguiça de quem preencheu, se estão incorretos ou se efetivamente tem algum significado. Creio que vai demandar uma certa pesquisa pra descobrir.

**Comment by fvall** [comment]
Ótimo, modo 2 em diante então

**Comment by leonardiwagner** [comment]
ainda sobre esse tema :stuck_out_tongue_closed_eyes: ...vale lembrar que a maioria das pessoas provavelmente irá acessar via mobile, ainda mais quando compartilhado nas mídias sóciais, eu sugiro tentar fazer os gráficos mobile-first e ter alguma opção "detalhes" pra aí sim ter esses detalhes

exemplo hoje:

![1](https://user-images.githubusercontent.com/2164551/83649023-1f296600-a58d-11ea-82f7-87ab2d5e7caa.jpg)

Idéia pensando em mobile:

- primeiro, agrupar dados que são muito pequenos

![2](https://user-images.githubusercontent.com/2164551/83649080-2fd9dc00-a58d-11ea-9833-45074403e9a4.jpg)

- segundo tem a questão de legibilidade, talvez ter uma identidade para cada grupo de dados (icones e cores), o "contra" é que sempre vai ter que ter uma "tradução" do dado bruto com a nossa associação:

![22](https://user-images.githubusercontent.com/2164551/83650467-c0fd8280-a58e-11ea-9b2b-614e85815fab.jpg)

- No detalhe, poderia acontecer 2 casos:
    - **A:**  Dado muito grande que "espreme" os outros, talvez colocar um limite, ex: o que for maior que 30%, limitar em 30% com algum tipo de sinalização especial, para os outros dados menores sejam visualizados de forma maior
    - **B:** Casos em que realmente há muitos dados, ao clicar abrir outro gráfico exclusivo para os "filhos"

![3](https://user-images.githubusercontent.com/2164551/83650513-ce1a7180-a58e-11ea-8e66-60f0ec5ce308.jpg)

**Comment by juliano** [comment]
Já chegou provando que não é apenas mais um belo bigode. O @fvall começou com esse gráfico porque precisávamos de algo acessando os dados "de verdade". Talvez haja algum gráfico melhor para mostrar os dados inicialmente?
